% #!/usr/bin/octave --persist
% Generated by BenfWaves - http://code.google.com/p/benfwaves
% Tested on Matlab R2013a

% Profile variables

{TemplateProfile}

% Data series

voltages = [ ...
{DataLines}
];

npoints = length(voltages);
times = ((0:(npoints-1)) + firstIndex - triggerIndex) / samplingFreq;
endtimes = [times(1), times(end)];
triglowpts = [triggerLow, triggerLow];
trighighpts = [triggerHigh, triggerHigh];

fname = ['DSO Nano Waveform/FFT plot: ' fileNumber];
FigHandle = figure('Name',fname,'Color',[.9 .9 .9]);
set(FigHandle, 'Position', [10, 10, 1300, 900]);
format shortG

txt1 = uicontrol('Style','text','Position',[20 600 200 20],'String',sprintfc('Voltage/Div: %.2d V', voltageDiv),'HorizontalAlignment','left','Backgroundcolor',[.9 .9 .9]);
txt2 = uicontrol('Style','text','Position',[20 575 200 20],'String',sprintfc('Attenuation: X%d', attenuation),'HorizontalAlignment','left','Backgroundcolor',[.9 .9 .9]);
txt3 = uicontrol('Style','text','Position',[20 550 200 20],'String',sprintfc('Time/Div: %.2d s', timeDiv),'HorizontalAlignment','left','Backgroundcolor',[.9 .9 .9]);
txt4 = uicontrol('Style','text','Position',[20 525 200 20],'String',sprintfc('Time of meas.: %.2d s', timeRange),'HorizontalAlignment','left','Backgroundcolor',[.9 .9 .9]);
txt5 = uicontrol('Style','text','Position',[20 500 200 20],'String',sprintfc('Num of Samples: %d ', sampleCount),'HorizontalAlignment','left','Backgroundcolor',[.9 .9 .9]);
txt6 = uicontrol('Style','text','Position',[20 475 200 20],'String',sprintfc('Sampling Freq.: %d Hz', samplingFreq),'HorizontalAlignment','left','Backgroundcolor',[.9 .9 .9]);
txt7 = uicontrol('Style','text','Position',[20 450 200 20],'String',sprintfc('Samples/Div: %d', sampPerDiv),'HorizontalAlignment','left','Backgroundcolor',[.9 .9 .9]);
txt8 = uicontrol('Style','text','Position',[20 425 200 20],'String',sprintfc('TriggerLevel: %.2d s', triggerLevel),'HorizontalAlignment','left','Backgroundcolor',[.9 .9 .9]);
txt9 = uicontrol('Style','text','Position',[20 400 200 20],'String',sprintfc('FastSampMode: %s', fastSampMode),'HorizontalAlignment','left','Backgroundcolor',[.9 .9 .9]);
txta = uicontrol('Style','text','Position',[20 375 200 20],'String',sprintfc('TriggerKind: %s', triggerKind),'HorizontalAlignment','left','Backgroundcolor',[.9 .9 .9]);
txtb = uicontrol('Style','text','Position',[20 350 200 20],'String',sprintfc('TriggerMode: %s', triggerMode),'HorizontalAlignment','left','Backgroundcolor',[.9 .9 .9]);
txtc = uicontrol('Style','text','Position',[20 325 200 20],'String',sprintfc('Firmware vers.: %s', firmware),'HorizontalAlignment','left','Backgroundcolor',[.9 .9 .9]);

subplot(3,1,1, 'Position', [0.21, 0.74, 0.75, 0.225])       % add Data plot in 3 x 1 grid  
plot(...
	endtimes, triglowpts,  'r', ...
	endtimes, trighighpts, 'r', ...
	   times, voltages,    'b'  ...
);
title('DSO Nano Waveform plot');
xlabel('Time (relative to trigger)');
ylabel('Voltage');
grid on;

subplot(3,1,2, 'Position', [0.21, 0.4, 0.75, 0.225])       % add FFT plot in 3 x 1 grid
N = 4096;
fs = samplingFreq;
freq = linspace(0,fs,N);
F = fft(voltages,N);
maxFreq = N;
plot(freq(1:maxFreq),abs(F(1:maxFreq)));
title('DSO Nano FFT plot');
ylabel('MAGNITUDE (DB)');
xlabel('FREQUENCY(Hz.)');
grid on;

subplot(3,1,3, 'Position', [0.21, 0.06, 0.75, 0.225])       % add FFT phase plot in 3 x 1 grid
phs = unwrap(angle(F));
lF = length(F);
f = (0:lF-1)/lF*fs;
plot(f,phs/pi)
title('DSO Nano FFT phase plot');
ylabel('Phase / \pi');
xlabel('Frequency(Hz.)');
grid on;