% #!/usr/bin/octave --persist
% Generated by BenfWaves - http://code.google.com/p/benfwaves
% Tested on Matlab R2013a
% Updated by SteliosVo

% Profile variables

{TemplateProfile}

% Data series

voltages = [ ...
{DataLines}
];

npoints = length(voltages);
times = ((0:(npoints-1)) + firstIndex - triggerIndex) / samplingFreq;
endtimes = [times(1), times(end)];
triglowpts = [triggerLow, triggerLow];
trighighpts = [triggerHigh, triggerHigh];

% Plot the data
fname = ['DSO Nano Waveform/FFT plot: ' fileNumber];
figure('Name',fname);
subplot(3,1,1)       % add Data plot in 3 x 1 grid
plot(...
	endtimes, triglowpts,  'r', ...
	endtimes, trighighpts, 'r', ...
	   times, voltages,    'b'  ...
);
title('DSO Nano Waveform plot');
xlabel('Time (relative to trigger)');
ylabel('Voltage');
grid on;

subplot(3,1,2)       % add FFT plot in 3 x 1 grid
N = 4096;
fs = samplingFreq;
freq = linspace(0,fs,N);
F = fft(voltages,N);
maxFreq = N;
plot(freq(1:maxFreq),abs(F(1:maxFreq)));
title('DSO Nano FFT plot');
ylabel('MAGNITUDE (DB)');
xlabel('FREQUENCY(Hz.)');
grid on;

subplot(3,1,3)       % add FFT phase plot in 3 x 1 grid
phs = unwrap(angle(F));
lF = length(F);
f = (0:lF-1)/lF*fs;
plot(f,phs/pi)
title('DSO Nano FFT phase plot');
ylabel('Phase / \pi');
xlabel('Frequency(Hz.)');
grid on;