#!/usr/bin/gnuplot -p
# Generated by BenfWaves - http://code.google.com/p/benfwaves
# Tested on gnuplot 4.4

reset

# Profile variables

{TemplateProfile}

# Plot data

set title 'DSO Nano Waveform: '.fileNumber
set xlabel 'Time (relative to trigger)'
set ylabel 'Voltage'
set grid
set style line 1 linetype 1 linecolor rgb 'blue' linewidth 2 # Solid
set style line 2 linetype 0 linecolor rgb 'red'  linewidth 2 # Dotted

if (triggerSens == 0) plot                             \
    triggerLevel title 'trig'  with lines linestyle 2; \
else plot                                              \
    triggerLow   title 'trig-' with lines linestyle 2, \
    triggerHigh  title 'trig+' with lines linestyle 2;

replot '-' using ((column(0) + firstIndex - triggerIndex)/samplingFreq):1 \
                 title ''      with lines linestyle 1;
{DataLines}
end
